apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: your-username/keptn-service-template-go:latest # Todo: Replace this with your image name
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
